services:
  client:
    container_name: client
    build: ./client
    restart: on-failure
    ports:
      - "3000:3000"
    command: serve -s build
    depends_on:
      - server

  server:
    container_name: server
    build: ./server
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./files:/app/server/files
      - ./attachments:/app/server/attachments
    command: uvicorn main:app --host 0.0.0.0 --port 8080